config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  devise_for :admins
  get 'callback' => 'home#callback'

  resources :users, only: [:index] do
    resources :chants, only: [:index, :show, :new, :create]
    post :change_rating, on: :member
  end
  # post 'chants' => 'chants#create'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chant.rb
class Chant < ApplicationRecord
  belongs_to :user

  mount_uploader :image, PosterUploader
end

app/models/poster.rb
class Poster < ApplicationRecord
  mount_uploader :image, PosterUploader
end

app/models/user.rb
class User < ApplicationRecord
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:vkontakte]
  has_many :chants

  mount_uploader :avatar, PosterUploader

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chants_controller.rb
class ChantsController < ApplicationController

  before_action :authenticate_admin!, only: [:index]
  before_action :authenticate_user!, only: [:new, :create]

  def index

  end

  def show
    @user = User.find(params[:user_id])
    @chant = Chant.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    if params[:user_id].to_i != current_user.id
      redirect_to new_user_chant_path(current_user)
    end
    @chant = Chant.new
    @countries = {'Австралия': 'aust', 'Англия': 'eng', 'Аргентина': 'arg', 'Бельгия': 'belg', 'Бразилия': 'bra', 'Германия': 'ger', 'Дания': 'dan', 'Египет': 'egy', 'Испания': 'spain', 'Иран': 'iran', 'Колумбия': 'col', 'Коста-Рика': 'kosta', 'Марокко': 'marok', 'Мексика': 'mex', 'Нигерия': 'nig', 'Панама': 'pan', 'Перу': 'peru', 'Польша': 'pol', 'Португалия': 'port', 'Россия': 'ru', 'Саудовская Аравия' => 'saudi', 'Сербия': 'serb', 'Синегал': 'sineg', 'Тунис': 'tun', 'Швейцария': 'switz', 'Швеция': 'swe', 'Уругвай': 'urug', 'Франция': 'fra', 'Хорватия': 'horv', 'Южная Корея': 'korea', 'Япония': 'jap'}
  end

  def create
    if user_signed_in?
      chant_params = params.require(:chant).permit!.to_h
      @chant = Services::CreateChant.call(current_user, chant_params)
      redirect_to user_chant_path(current_user, @chant)
    else
      redirect_to 'https://oauth.vk.com/authorize?client_id=6609013&display=popup&redirect_uri=https%3A%2F%2Ffootball-chatbot.herokuapp.com%2Fcallback&response_type=code&scope=friends%2Cphotos%2Cgroups&v=5.80'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_admin!

  def index
    # unless user_signed_in?
    #   @user = Services::CreateUser.call(28833104, 'aa@bb.com', 'ab99173579e1ef34aa089605bdb5d07a5078ecbac4b69ba4db6e1d0196e655b0657bd34dfb9da23ff80f1')
    #   sign_in_and_redirect @user, event: :authentication
    # end
    @chants = Chant.order('created_at DESC')
    @best_users = User.order('rating').limit(10)
    @new_users = User.order('created_at DESC').limit(8)
  end

  def callback
    url = "https://oauth.vk.com/access_token?client_id=#{ENV['VK_APP_ID']}&client_secret=#{ENV['VK_APP_SECRET']}&redirect_uri=https%3A%2F%2Ffootball-chatbot.herokuapp.com%2Fcallback&code=#{params[:code]}"
    uri = URI.parse(url)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    response = http.request(Net::HTTP::Get.new(uri.request_uri))
    response = JSON.parse(response.body)
    if response['access_token']
      @user = Services::CreateUser.call(response['user_id'], response['email'], response['access_token'])
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "Vkontakte"
      sign_in_and_redirect @user, event: :authentication
    else
      flash[:notice] = 'Ошибка'
      redirect_to root_path
    end
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def vkontakte
    @user = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "Vkontakte"
      sign_in_and_redirect root_path, event: :authentication
    else
      flash[:notice] = "Authentication Error"
      redirect_to root_path
    end
  end

end

app/controllers/posters_controller.rb
class PostersController < ApplicationController

  def index

  end

  def show
    @poster = Poster.find(params[:id])
  end

  def create
    username = params[:poster][:username]
    user_id = Poster.count
    img = Magick::Image.read(Rails.root + 'public/test.jpg').first

    copyright = Magick::Draw.new
    copyright.annotate(img, 0, 0, 100, 280, username) do
      self.font = 'Georgia'
      self.pointsize = 24
      self.font_weight = Magick::BoldWeight
      self.fill = 'white'
      self.gravity = Magick::SouthEastGravity
    end
    img.write(Rails.root + "public/test#{user_id}.jpg")
    poster_image = File.open(Rails.root + "public/test#{user_id}.jpg")
    @poster = Poster.create(user_id: user_id, username: username, image: poster_image)
    redirect_to @poster
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @users = User.order('rating')
  end

  def show
    @user = User.find(params[:id])
  end

  def change_rating
    @user = User.find(params[:id])
    rating = @user.rating.is_a?(Integer) ? @user.rating + 1 : 1
    @user.update_attributes(rating: rating)
    render json: 'success', status: 200
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chants_helper.rb
module ChantsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_controller_helper.rb
module OmniauthCallbacksControllerHelper
end

app/helpers/posters_helper.rb
module PostersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chants/new.html.erb
<section id='first' class='create_slogan_page'>
  <div class='container'>
    <div class='row'>
      <div class='col-lg-7 main_person'>
        <div class='photo_p'>
          <a href="https://vk.com/id<%= current_user.uid %>" target="_blank">
            <%= image_tag(current_user.avatar.url, alt: 'Photo') %>
            <div class="points"><%= current_user.rating || 0 %></div>
          </a>
        </div>
        <div class='text_p'>
          <h2><a href="https://vk.com/id<%= current_user.uid %>" target="_blank"><%= current_user.full_name %></a></h2>
          <p>Для создания твоей кричалки выбери 2 страны, за которые ты болеешь.</p>
        </div>
        <div class='slogan'>
          <pre>???</pre>
        </div>
      </div>
      <div class="col-lg-5 offset-lg-0 col-10 offset-1 align-self-end create_s">
        <%= form_for [current_user, @chant] do |f| %>
          <%= f.hidden_field :country1, required: true %>
          <%= f.hidden_field :country2, required: true %>
          <div class='country_container'>
            <input type='text' id='country1' name='country1' class='country_checkbox'/>
            <label class='country' for='country1'></label>
            <input type='text' id='country2' name='country2' class='country_checkbox'/>
            <label class='country' for='country2'></label>
          </div>
          <p class=''>Почти готово, жми на кнопку, расшарь на своей странице в Вконтакте и выиграй призы!</p>
          <div>
            <div class='error_message'>
              <p>Не заполнены все поля и убедитесь, что вы согласились на обработку персональных данных</p>
            </div>
            <%= f.submit 'Готово', class: 'ready disabled', disabled: true, id: 'form-submit' %>
          </div>
          <label>
            <input type='checkbox' name='agreement' id="checkbox" onclick="checkDisable()"/>
            Согласен на обработку персональных данных
          </label>
        <% end %>
      </div>
      <div class='choose_country col-lg-5'>
        <p class='choose_title'>Выбери страну</p>
        <div class='country_list'>
          <div class='clearfix'>
            <% @countries.each do |k, v| %>
              <div class='country_item'>
                <a href='<%= v %>'>
                  <%= image_tag("country/#{v}.png") %>
                  <p><%= k %></p>
                </a>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
    function checkDisable() {
        if ($('#checkbox').is(':checked')) {
            $('#form-submit').removeAttr("disabled");
            $('#form-submit').removeClass("disabled");
        }
        else {
            $('#form-submit').attr("disabled", "disabled");
            $('#form-submit').addClass("disabled");
        }
    }
</script>

app/views/chants/show.html.erb
<section id='first'>
  <div class='container'>
    <div class='row'>
      <div class='col-12 main_person'>
        <div class='photo_p'>
          <a href="https://vk.com/id<%= @user.uid %>" target="_blank">
            <%= image_tag(@user.avatar.url, alt: 'Photo') %>
            <div class="points"><%= @user.rating || 0 %></div>
          </a>
        </div>
        <div class='text_p'>
          <h2>
            <a href="https://vk.com/id<%= @user.uid %>" target="_blank"><%= @user.full_name %></a>
          </h2>
          <p>Создал<%= 'а' if @user.sex == '1' %> свою кричалку к чемпионату мира по футболу.</p>
          <p>Пригласил<%= 'а' if @user.sex == '1' %>: <%= @user.rating || 0 %> чел.</p>
        </div>
      </div>
      <div class='col-md-1 align-self-end'>
        <%= link_to 'Скачать', @chant.image.url, download: "chant_#{@chant.id}", class: 'download_link' %>
      </div>
      <div class='col-lg-8 slogan'>
        <pre><%= @chant.text %></pre>
      </div>
      <div class='col-lg-3 share align-self-end'>
        <% if user_signed_in? && @user == current_user %>
          <div class="a2a_kit a2a_kit_size_28 a2a_default_style"
               data-a2a-title='Создай свою футбольную кричалку!'>
            <a class="a2a_button_vk"><img src='/images/vk.png' alt='Вконтакте'/></a>
            <a class="a2a_button_facebook"><img src='/images/fb.png' alt='Facebook'/></a>
            <a class="a2a_button_twitter"><img src='/images/twi.png' alt='Twitter'/></a>
            <a class="a2a_button_odnoklassniki"><img src='/images/ok.png' alt='Одноклассники'/></a>
          </div>
          <script async src="https://static.addtoany.com/menu/page.js"></script>
          <div class='share_text'>
            <p><span>Поделись</span></p>
            <p>и выиграй призы</p>
          </div>
          <input type='text' id='clip_input'/>
          <div class='copy' data-clipboard-target="#clip_input">copy</div>
        <% else %>
          <div class="share_text"><p>Создай свою кричалку!</p></div>
          <% if user_signed_in? %>
            <%= link_to 'Создать', new_user_chant_path(current_user), class: 'button' %>
          <% else %>
            <a class="button" href="https://oauth.vk.com/authorize?client_id=6609013&display=popup&redirect_uri=https%3A%2F%2Ffootball-chatbot.herokuapp.com%2Fcallback&response_type=code&scope=friends%2Cphotos%2Cgroups%2Cemail&v=5.80">Создать</a>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

<% if !user_signed_in? && request.params['invite'] && User.find_by(invite_code: request.params['invite']) %>
  <script>
      window.localStorage.setItem('invite', '<%= @user.id %>');
  </script>
<% end %>
<% if user_signed_in? && @chant == current_user.chants.first %>
  <script>
      if (window.localStorage.key('invite')) {
          console.log('invite');
          axios.post('/users/' + window.localStorage.getItem('invite') + '/change_rating')
              .then(function (response) {
                  console.log(response);
              })
              .catch(function (error) {
                  console.log(error);
              });
          window.localStorage.clear();
      }
  </script>
<% end %>

app/views/home/index.html.erb
<section id='first'>
  <div class='container'>
    <div class='row justify-content-center align-items-center'>
      <div class='col-lg-9 create'>
        <h1 style="width: auto;">создай свою оригинальную кричалку</h1>
        <% if user_signed_in? %>
          <%= link_to 'Создать', new_user_chant_path(current_user), class: 'button', style: 'width: 40%' %>
        <% else %>
          <a class="button" href="https://oauth.vk.com/authorize?client_id=6609013&display=popup&redirect_uri=https%3A%2F%2Ffootball-chatbot.herokuapp.com%2Fcallback&response_type=code&scope=friends%2Cphotos%2Cgroups%2Cemail&v=5.80" style="width: 40%;">Создать</a>
        <% end %>
        <p>
          Потребуется вход через социальную сеть Вконтакте. На основе анализа Вашего профиля будет создана
          персонализированная кричалка. Поделитесь ею на своей странице, чтобы выиграть призы. Поделитесь с друзьями
          своей персональной ссылкой. За каждого друга, который так же создаст кричалку, мы начислим Вам 1 балл.
          Собиарайте баллы, взойдите на Олимп и получите призы!
        </p>
      </div>
    </div>

    <div class='col-md-6 offset-md-3 create mobile_block'>
      <h1>создай свою оригинальную <span>кричалку</span></h1>
      <% if user_signed_in? %>
        <%= link_to 'Создать', new_user_chant_path(current_user), class: 'button' %>
      <% else %>
        <a class="button" href="https://oauth.vk.com/authorize?client_id=6609013&display=popup&redirect_uri=https%3A%2F%2Ffootball-chatbot.herokuapp.com%2Fcallback&response_type=code&scope=friends%2Cphotos%2Cgroups%2Cemail&v=5.80">Создать</a>
      <% end %>
    </div>
    <h3>Новые пользователи</h3>
    <div class='users_row'>
      <% @new_users.each do |user| %>
        <div class='photo_p'>
          <a href="https://vk.com/id<%= user.uid %>" target="_blank">
            <%= image_tag(user.avatar.url, alt: 'Photo') %>
            <div class="points"><%= user.rating || 0 %></div>
          </a>
        </div>
      <% end %>
    </div>
    <h3>Последние кричалки</h3>
    <div class='slogan_slider'>
      <% @chants.limit(40).each_slice(2) do |fchant, schant| %>
        <div class='slogan_slide'>
          <div class='slogan_link'>
            <%= link_to user_chant_path(fchant.user, fchant) do %>
              <%= image_tag(fchant.image.url) %>
            <% end %>
            <% if schant %>
              <%= link_to user_chant_path(schant.user, schant) do %>
                <%= image_tag(schant.image.url) %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <h3 class='no_margin'>рейтинг пользователей</h3>
    <div class='row rating_con'>
      <% @best_users.each_with_index do |user, i| %>
        <div class='col-lg-6 offset-lg-3 rating'>
          <div>
            <div class='photo_p'>
              <a href="https://vk.com/id<%= user.uid %>" target="_blank">
                <%= image_tag(user.avatar.url, alt: 'Photo') %>
                <div class="points"><%= user.rating || 0 %></div>
              </a>
            </div>
            <div class='text_p'>
              <h2>
                <a href="https://vk.com/id<%= user.uid %>" target="_blank"><%= user.full_name %></a>
              </h2>
            </div>
            <div class='place'><%= i + 1 %></div>
          </div>
        </div>
      <% end %>
    </div>
    <div class='more'>
      <%= link_to '●●●', users_path %>
    </div>
    <div class='ball_footer'>
      <img src='images/ball_footer.png' alt='Ball'/>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width">
  <meta property="og:title" content="Создай свою футбольную кричалку!"/>
  <meta property="og:type" content="website"/>
  <meta property="og:description" content="Поделись с друзьями, выиграй призы, заработай рейтинг!"/>
  <% if @chant && request.fullpath != new_user_chant_path(current_user) %>
    <meta property="og:url" content="http://football.makemedia.agency<%= user_chant_path(@chant.user, @chant) %>"/>
    <meta property="og:image" content="<%= @chant.image.url %>"/>
  <% end %>
  <title>Создай свою футбольную кричалку!</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': false %>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <link rel="stylesheet" type="text/css" href="/slick/slick.css">
</head>

<body>
<%# link_to 'Выйти', destroy_admin_session_path, method: :delete if admin_signed_in? %>
<%# current_user.firstname if user_signed_in? %>
<%# image_tag(current_user.avatar.url) if user_signed_in? %>


<%# link_to 'Войти через ВК', user_vkontakte_omniauth_authorize_path %>
<!--<a href="https://oauth.vk.com/authorize?client_id=6609013&display=popup&redirect_uri=https%3A%2F%2Ffootball-chatbot.herokuapp.com%2Fcallback&response_type=code&scope=friends%2Cphotos%2Cgroups&v=5.80">Войти-->
<!--через ВКонтакте</a><br/>-->
<%# link_to 'Создать свою кричалку', chants_path, method: :post %>
<header>
  <div id='bg_parallax'>
    <div data-depth="0.1"></div>
  </div>
  <div id="parallax">
    <img src='/images/footballer.png' class='footballer' data-depth="0.4" alt='Футболист'/>
    <img src='/images/ball.png' class='ball_header' data-depth="0.4" alt='Мяч'/>
  </div>
  <div class='container'>
    <div class='row justify-content-end align-items-end'>
      <div class='col-lg-4 create'>
        <p>Создано в <a href='#'>ММА</a></p>
      </div>
    </div>
  </div>
</header>

<%= yield %>

<%= link_to "Выйти", destroy_user_session_path, method: :delete if user_signed_in? %>
<%= javascript_include_tag 'custom/parallax.min' %>
<script src="https://cdn.jsdelivr.net/npm/clipboard@1/dist/clipboard.min.js"></script>
<script type="text/javascript" src='/slick/slick.min.js'></script>
<%= javascript_include_tag 'custom/script' %>
</body>
</html>

app/views/posters/show.html.erb
<%= image_tag(@poster.image.url) %>

app/views/users/index.html.erb
<section id='first'>
  <div class='container'>
    <h3 class='no_margin'>рейтинг пользователей</h3>
    <div class='row rating_con'>
      <% @users.each_with_index do |user, i| %>
        <div class='col-lg-6 offset-lg-3 rating'>
          <div>
            <div class='photo_p'>
              <a href="https://vk.com/id<%= user.uid %>" target="_blank">
                <%= image_tag(user.avatar.url, alt: 'Photo') %>
                <div class="points"><%= user.rating || 0 %></div>
              </a>
            </div>
            <div class='text_p'>
              <h2>
                <a href="https://vk.com/id<%= user.uid %>" target="_blank"><%= user.full_name %></a>
              </h2>
            </div>
            <div class='place'><%= i + 1 %></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<%= @user.full_name %>
<%# link_to 'Создать свою кричалку', user_chants_path(), method: :post, id: 'createChantViaFriend' %><br/>

<script>
  $('#createChantViaFriend').click(function(){window.localStorage.setItem('invite', '<%= @user.id %>')})
</script>